version: '3'

services:
  mongo:
    image: mongo
    
    image: muguirajames/mongojam
    build:
      context: .
      dockerfile: Dockerfile-mongo.yml

    environment:
      - MONGO_INITDB_ROOT_USERNAME=root 
      - MONGO_INITDB_ROOT_PASSWORD=mysql
      - MONGO_INITDB_DATABASE=muse
      - DATABASE_USERNAME=magoo
      - DATABASE_PASSWORD=q1w2e3r4t5y6

    ports:
      - 27017:27017
  